name: JoyStickHub
version: 1.6.0-p2
main: fm.joystick.hub.JoyStickHub
api-version: '1.20'
description: JoyStickHub P2 - Spawns centralisés, Moteur Parkour et Protections zones d'accueil
softdepend:
  - ItemJoin
  - Multiverse-Inventories
  - AuthMe
  - WorldEdit
commands:
  parkour:
    description: Commandes du moteur de parkour JoyStick FM
    usage: /parkour [quit|status|reload]
    aliases: [pk]
  jhub:
    description: Commandes d'administration et d'import de JoyStickHub
    usage: /jhub [paste|reload]
    permission: joystickhub.admin
